config/routes.rb
Rails.application.routes.draw do
  resources :file_inputs
  resources :file_inputs, only: [:index, :new, :create, :show]

  root "file_inputs#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/file_input.rb
# frozen_string_literal: true

require_relative '../../lib/file_parser'

class FileInput < ApplicationRecord
  has_many :purchases, dependent: :destroy

  def purchases
    @purchases = Purchase.where(file_input_id: id).includes(:purchaser, :item, :merchant)
  end

  def gross_income
    purchases.includes(:item).map(&:income).sum
  end

  def self.process_purchases(file, file_input_id)
    sales = FileParser.new(file).content
    sales.each do |sale|
      params = set_params(sale, file_input_id)

      Purchase.register(params)
    end
  end

  def self.set_params(sale_data, file_input_id)
    {
      purchaser_name: sale_data[0],
      item_description: sale_data[1],
      item_price: sale_data[2].to_f,
      purchase_count: sale_data[3].to_i,
      merchant_address: sale_data[4],
      merchant_name: sale_data[5],
      file_input_id:
    }
  end

  private_class_method :set_params
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :description, presence: true
  validates :price_in_cents, presence: true

  has_many :purchases

  def price
    (price_in_cents.to_f / 100)
  end

  def self.find_or_create(params)
    items = where(description: params[:item_description])
    params_price = (params[:item_price] * 100).to_i

    return Item.create(description: params[:item_description], price_in_cents: params_price) if items.empty?

    items.map do |item|
      return item if params_price == item.price_in_cents

      Item.create(description: params[:item_description], price_in_cents: params_price)
    end.first
  end
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true

  has_many :purchases

  def self.find_or_create(params)
    find_by(name: params[:merchant_name]) || create(
      name: params[:merchant_name],
      address: params[:merchant_address]
    )
  end
end

app/models/purchase.rb
# frozen_string_literal: true

class Purchase < ApplicationRecord
  belongs_to :purchaser
  belongs_to :item
  belongs_to :merchant
  belongs_to :file_input

  validates :count, presence: true

  def income
    (item.price * count)
  end

  def self.register(params)
    create(
      purchaser: Purchaser.find_or_create(params),
      item: Item.find_or_create(params),
      count: params[:purchase_count],
      merchant: Merchant.find_or_create(params),
      file_input: FileInput.find(params[:file_input_id])
    )
  end

  def self.total_gross_income
    all.includes(:item).map do |purchase|
      (purchase.item.price * purchase.count)
    end.sum
  end
end

app/models/purchaser.rb
# frozen_string_literal: true

class Purchaser < ApplicationRecord
  validates :name, presence: true

  has_many :purchases

  def self.find_or_create(params)
    find_by(name: params[:purchaser_name]) || create(name: params[:purchaser_name])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/file_inputs_controller.rb
# frozen_string_literal: true

class FileInputsController < ApplicationController
  before_action :find_file_input, only: %i[show destroy]

  def index
    @file_inputs = FileInput.all.includes(:purchases)
  end

  def show; end

  def new
    @file_input = FileInput.new
  end

  def create # rubocop:disable Metrics/MethodLength, Metrics/AbcSize
    file = params[:file_input][:file]
    params[:file_input].delete(:file)

    @file_input = FileInput.new(file_input_params)

    respond_to do |format|
      if @file_input.save
        FileInput.process_purchases(file, @file_input.id)

        format.html { redirect_to file_input_url(@file_input), notice: I18n.t(:success_file_insert) }
        format.json { render :show, status: :created, location: @file_input }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @file_input.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @file_input.destroy

    respond_to do |format|
      format.html { redirect_to file_inputs_url, notice: I18n.t(:success_file_destroy) }
      format.json { head :no_content }
    end
  end

  private

  def find_file_input
    @file_input = FileInput.find(params[:id])
  end

  def file_input_params
    params.fetch(:file_input, {})
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/file_inputs/_file_input.html.erb
<div id="<%= dom_id file_input %>">
  <table>
    <thead>
      <tr>
        <th>Purchaser</th>
        <th>Item Description</th>
        <th>Item Price</th>
        <th>Count</th>
        <th>Merchant Name</th>
        <th>Merchant Address</th>
      </tr>
    </thead>
    <tbody>
      <% @file_input.purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.purchaser.name %></td>
        <td><%= purchase.item.description %></td>
        <td><%= purchase.item.price %></td>
        <td><%= purchase.count %></td>
        <td><%= purchase.merchant.name %></td>
        <td><%= purchase.merchant.address %></td>
      </tr>
      <% end %>
    </tbody>
    <div>
      <p>
        <strong>Gross income from this file:</strong>
        <%= "US$ #{file_input.gross_income}" %>
      </p>
      <p>
        <strong>Total gross income:</strong>
        <%= "US$ #{Purchase.total_gross_income}" %>
      </p>
    </div>
  </table>
</div>

app/views/file_inputs/_form.html.erb
<%= form_with(model: file_input) do |form| %>
  <% if file_input.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(file_input.errors.count, "error") %> prohibited this file_input from being saved:</h2>

      <ul>
        <% file_input.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.file_field :file, required: true %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/file_inputs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inserted Files</h1>

<div id="file_inputs">
  <table>
    <thead>
      <tr>
        <th>Insertion Date</th>
        <th>Gross Income</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @file_inputs.each do |file_input| %>
        <tr>
          <td><%= file_input.created_at.strftime("%d/%m/%Y %H:%M UTC") %></td>
          <td><%= "US$#{file_input.gross_income}" %></td>
          <td><%= link_to "Show", file_input %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <strong>Total gross income:</strong>
    <%= "US$ #{Purchase.total_gross_income}" %>
  </div>

</div>

<%= link_to "Insert new file", new_file_input_path %>

app/views/file_inputs/new.html.erb
<h1>Insert new file</h1>

<%= render "form", file_input: @file_input %>

<br>

<div>
  <%= link_to "Back", file_inputs_path %>
</div>

app/views/file_inputs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @file_input %>

<div>
  <%= link_to "Back", file_inputs_path %>
  <%=
    button_to "Destroy",
    @file_input,
    data: { turbo_confirm: 'Are you sure?' },
    method: :delete
  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesRecord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>